--- 
apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "nginx4"
  labels: 
    app: "nginx4"
spec: 
  selector: 
    matchLabels: 
      app: "nginx"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "nginx"
    spec: 
      containers: 
        - 
          name: "nginx"
          image: "nginx"
          ports: 
            - 
              containerPort: 80
          volumeMounts: []
      volumes: []
